feeds:
  type: rest
  prefix: /v1
  resource:     "ArthurHoaroRssCruncherApiBundle:Feed"
  name_prefix:  api_1_
articles:
  type: rest
  prefix: /v1
  resource:     "ArthurHoaroRssCruncherApiBundle:Article"
  name_prefix:  api_1_