parameters:
  arthur_hoaro_rss_cruncher_api.handler.package: ArthurHoaro\RssCruncherApiBundle\Handler\
  arthur_hoaro_rss_cruncher_api.entity.package: ArthurHoaro\RssCruncherApiBundle\Entity\
  arthur_hoaro_rss_cruncher_api.type.package: ArthurHoaro\RssCruncherApiBundle\Form\
  arthur_hoaro_rss_cruncher_api.feed.handler.class: '%arthur_hoaro_rss_cruncher_api.handler.package%FeedHandler'
  arthur_hoaro_rss_cruncher_api.feed.class: '%arthur_hoaro_rss_cruncher_api.entity.package%Feed'
  arthur_hoaro_rss_cruncher_api.feed.type.class: '%arthur_hoaro_rss_cruncher_api.type.package%FeedType'
  arthur_hoaro_rss_cruncher_api.article.handler.class: '%arthur_hoaro_rss_cruncher_api.handler.package%ArticleHandler'
  arthur_hoaro_rss_cruncher_api.article.class: '%arthur_hoaro_rss_cruncher_api.entity.package%Article'
  arthur_hoaro_rss_cruncher_api.article.type.class: '%arthur_hoaro_rss_cruncher_api.type.package%ArticleType'
  arthur_hoaro_rss_cruncher_api.proxy_user.handler.class: '%arthur_hoaro_rss_cruncher_api.handler.package%ProxyUserHandler'
  arthur_hoaro_rss_cruncher_api.proxy_user.class: '%arthur_hoaro_rss_cruncher_api.entity.package%ProxyUser'
  arthur_hoaro_rss_cruncher_api.access_token.handler.class: '%arthur_hoaro_rss_cruncher_api.handler.package%AccessTokenHandler'
  arthur_hoaro_rss_cruncher_api.access_token.class: '%arthur_hoaro_rss_cruncher_api.entity.package%AccessToken'
  arthur_hoaro_rss_cruncher_api.user_feed.handler.class: '%arthur_hoaro_rss_cruncher_api.handler.package%UserFeedHandler'
  arthur_hoaro_rss_cruncher_api.user_feed.class: '%arthur_hoaro_rss_cruncher_api.entity.package%UserFeed'
  arthur_hoaro_rss_cruncher_api.user_feed.type.class: '%arthur_hoaro_rss_cruncher_api.type.package%UserFeedType'
  arthur_hoaro_rss_cruncher_api.category.handler.class: '%arthur_hoaro_rss_cruncher_api.handler.package%FeedCategoryHandler'
  arthur_hoaro_rss_cruncher_api.category.class: '%arthur_hoaro_rss_cruncher_api.entity.package%FeedCategory'
  arthur_hoaro_rss_cruncher_api.category.type.class: '%arthur_hoaro_rss_cruncher_api.type.package%FeedCategoryType'
  database_dsn: 'pgsql:'
services:
  arthur_hoaro_rss_cruncher_api.feed.handler:
    class: '%arthur_hoaro_rss_cruncher_api.feed.handler.class%'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%arthur_hoaro_rss_cruncher_api.feed.class%'
      - '@form.factory'
      - '%arthur_hoaro_rss_cruncher_api.feed.type.class%'
      - '%kernel.cache_dir%'
  arthur_hoaro_rss_cruncher_api.article.handler:
    class: '%arthur_hoaro_rss_cruncher_api.article.handler.class%'
    arguments: ['@doctrine.orm.entity_manager', '%arthur_hoaro_rss_cruncher_api.article.class%', '@form.factory', '%arthur_hoaro_rss_cruncher_api.article.type.class%']
  arthur_hoaro_rss_cruncher_api.proxy_user.handler:
    class: '%arthur_hoaro_rss_cruncher_api.proxy_user.handler.class%'
    arguments: ['@doctrine.orm.entity_manager', '%arthur_hoaro_rss_cruncher_api.proxy_user.class%', '', '']
  arthur_hoaro_rss_cruncher_api.access_token.handler:
    class: '%arthur_hoaro_rss_cruncher_api.access_token.handler.class%'
    arguments: ['@doctrine.orm.entity_manager', '%arthur_hoaro_rss_cruncher_api.access_token.class%', '', '']
  arthur_hoaro_rss_cruncher_api.user_feed.handler:
    class: '%arthur_hoaro_rss_cruncher_api.user_feed.handler.class%'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%arthur_hoaro_rss_cruncher_api.user_feed.class%'
      - '@form.factory'
      - '%arthur_hoaro_rss_cruncher_api.user_feed.type.class%'
  arthur_hoaro_rss_cruncher_api.category.handler:
      class: '%arthur_hoaro_rss_cruncher_api.category.handler.class%'
      arguments:
            - '@doctrine.orm.entity_manager'
            - '%arthur_hoaro_rss_cruncher_api.category.class%'
            - '@form.factory'
            - '%arthur_hoaro_rss_cruncher_api.category.type.class%'
  arthur_hoaro_rss_cruncher_api.queue_manager:
    class: ArthurHoaro\RssCruncherApiBundle\Service\MessagingService
    arguments:
      - '%database_dsn%'
      - '%database_host%'
      - '%database_port%'
      - '%database_name%'
      - '%database_user%'
      - '%database_password%'
