ArthurHoaro\RssCruncherApiBundle\Entity\UserFeed:
  properties:
#    sitename:
#      - NotBlank: ~
#      - NotNull: ~
#      - Length:
#          min: 1
#          max: 50
#          minMessage: "Your sitename must be at least  characters length"
#          maxMessage: "Your sitename cannot be longer than  characters length"
#    siteurl:
#      - NotBlank: ~
#      - NotNull: ~
#      - Url: ~
#      - Length:
#          min: 5
#          max: 2000
#          minMessage: "Your siteurl must be at least {{ limit }} characters length"
#          maxMessage: "Your siteurl cannot be longer than {{ limit }} characters length"
#    feedname:
#      - NotBlank: ~
#      - NotNull: ~
#      - Length:
#          min: 1
#          max: 50
#          minMessage: "Your feedname must be at least {{ limit }} characters length"
#          maxMessage: "Your feedname cannot be longer than {{ limit }} characters length"
#    feedurl:
#      - NotBlank: ~
#      - NotNull: ~
#      - Url: ~
#      - Length:
#          min: 5
#          max: 2000
#          minMessage: "Your siteurl must be at least {{ limit }} characters length"
#          maxMessage: "Your siteurl cannot be longer than {{ limit }} characters length"
ArthurHoaro\RssCruncherApiBundle\Entity\Article:
  properties:
    title:
      - NotBlank: ~