services:
  arthur_hoaro_rss_cruncker_fos_security:
    class: FOS\UserBundle\Controller\SecurityController
    calls:
      - [setContainer, ["@service_container"]]
  oauth_event_listener:
    class:  ArthurHoaro\RssCruncherUserBundle\EventListener\OAuthEventListener
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }

