<?php

namespace ArthurHoaro\RssCruncherApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends EntityRepository
{
    /**
     * @param ProxyUser $proxyUser
     *
     * @return Article[]
     */
    public function findByUser($proxyUser)
    {
        $dql  = 'SELECT f FROM ArthurHoaroRssCruncherApiBundle:Feed f ';
        $dql .= 'JOIN f.proxyUsers pu ';
        $dql .= 'WHERE pu.client = :client AND pu.user = :user';
        $query = $this->_em->createQuery($dql);
        $query->setParameter('client', $proxyUser->getClient());
        $query->setParameter('user', $proxyUser->getUser());
        return $query->getResult();
    }
}
