<?php

namespace ArthurHoaro\RssCruncherApiBundle\Entity;

use ArthurHoaro\RssCruncherApiBundle\Helper\FeedHelper;
use ArthurHoaro\RssCruncherApiBundle\Helper\StringUtil;
use ArthurHoaro\RssCruncherApiBundle\Helper\UrlCleaner;
use Doctrine\ORM\EntityRepository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends EntityRepository
{
    public function findByUrl($url) {
        return $this->findOneBy([
            'feedurl' => $url,
            'enabled' => true,
        ]);
    }

    public function findByUrlOrCreate($url) {
        $urlObj = new UrlCleaner($url);
        $cleanUrl = $urlObj->cleanup(false);
        $feed = $this->findByUrl($cleanUrl);
        if (!empty($feed)) {
            return $feed;
        }

        return $this->createFeed($url, $urlObj->isHttps());
    }

    private function createFeed($cleanUrl, $isHttps)
    {
        $entity = new Feed();
        $entity->setFeedurl($cleanUrl);
        $entity->setHttps($isHttps);
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }
}
