feeds:
  type: rest
  prefix: /v1
  resource:     "ArthurHoaroFeedsApiBundle:Feed"
  name_prefix:  api_1_
articles:
  type: rest
  prefix: /v1
  resource:     "ArthurHoaroFeedsApiBundle:Article"
  name_prefix:  api_1_